### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by mushishi78** [henrythemes/jekyll-starter-theme#1]
Would it be possible for you to add a licence file to this and your other Jekyll repos listed on jekyllthemes? I'd greatly appreciate it, thanks.

**Comment by geraldb** [comment]
Thanks for the suggestion. The theme is "un" licensed. There's no license, no copyright, no rights reserved. It's public domain e.g.the "License" in the README reads: The starter theme is dedicated to the public domain. Use it as you please with no restrictions whatsoever. That's it. There's no dedicated file. Does this anchor link work for you? - [planetjekyll/jekyll-starter-theme/README.md#meta](https://github.com/planetjekyll/jekyll-starter-theme/blob/gh-pages/README.md#meta)

**Comment by mushishi78** [comment]
Oh okay. I'm not lawyer so I'll just accept that that's a thing. I'll use that anchor thanks.

**Comment by geraldb** [comment]
Great. I've added a new anchor (e.g. #license) so you can use license as expected. Thanks. The link is    [github.com/planetjekyll/jekyll-starter-theme/blob/gh-pages/README.md#license](https://github.com/planetjekyll/jekyll-starter-theme/blob/gh-pages/README.md#license) or [github.com/planetjekyll/jekyll-starter-theme/#license](https://github.com/planetjekyll/jekyll-starter-theme/#license) using the implied README on the repo page.
